FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o receiver ./cmd/receiver

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/receiver .

ENTRYPOINT ["./receiver"]
